# SPDX-FileCopyrightText: 2026 Kaito Udagawa <umireon@kaito.tokyo>
#
# SPDX-License-Identifier: Apache-2.0

name: Start ciproxy
author: Kaito Udagawa <umireon@kaito.tokyo>
description: Start ciproxy for vcpkg binary caching

inputs:
  master-token:
    description: "Long-term master token"
    required: true
  ciproxy-dir:
    description: "Directory of ciproxy"
    required: true
  port:
    description: "Port to listen on"
    required: true

outputs:
  ciproxy-pid:
    description: "PID of the started ciproxy"
    value: ${{ steps.start.outputs.ciproxy-pid }}
  ciproxy-stdout-log:
    description: "Path to ciproxy stdout log"
    value: ${{ inputs.ciproxy-dir }}/stdout.log
  ciproxy-stderr-log:
    description: "Path to ciproxy stderr log"
    value: ${{ inputs.ciproxy-dir }}/stderr.log

runs:
  using: composite
  steps:
    - name: Start ciproxy
      id: start
      shell: bash --noprofile --norc -euo pipefail {0}
      working-directory: ${{ inputs.ciproxy-dir }}
      env:
        MASTER_TOKEN: ${{ inputs.master-token }}
        EXE: ${{ runner.os == 'Windows' && '.exe' || '' }}
        PORT: ${{ inputs.port }}
      run: |
        go build
        MASTER_TOKEN="$MASTER_TOKEN" "./ciproxy$EXE" > stdout.log 2> stderr.log &
        CIPROXY_PID=$!
        echo "Ciproxy started with PID: $CIPROXY_PID"
        echo "ciproxy-pid=$CIPROXY_PID" >> "$GITHUB_OUTPUT"
        sleep 3
