# SPDX-FileCopyrightText: 2026 Kaito Udagawa <umireon@kaito.tokyo>
#
# SPDX-License-Identifier: Apache-2.0

name: Start ciproxy
author: Kaito Udagawa <umireon@kaito.tokyo>
description: Start ciproxy for vcpkg binary caching

inputs:
  master-token:
    description: "Long-term master token"
    required: true
  ciproxy-dir:
    description: "Directory of ciproxy"
    required: true
  ciproxy-port:
    description: "Port to listen on"
    required: true

outputs:
  CIPROXY_PID:
    description: "PID of the started ciproxy"
    value: ${{ runner.os == 'Windows' && steps.start-windows.outputs.CIPROXY_PID || steps.start-non-windows.outputs.CIPROXY_PID }}
  CIPROXY_PORT:
    description: "Port that ciproxy is listening on"
    value: ${{ inputs.ciproxy-port }}
  CIPROXY_STDOUT_LOG:
    description: "Path to ciproxy stdout log"
    value: ${{ inputs.ciproxy-dir }}/stdout.log
  CIPROXY_STDERR_LOG:
    description: "Path to ciproxy stderr log"
    value: ${{ inputs.ciproxy-dir }}/stderr.log

runs:
  using: composite
  steps:
    - name: Check if MASTER_TOKEN is set
      shell: bash --noprofile --norc -euo pipefail {0}
      env:
        MASTER_TOKEN: ${{ inputs.master-token }}
      run: '[[ -n "$MASTER_TOKEN" ]]'

    - name: Start ciproxy (Windows)
      id: start-windows
      if: runner.os == 'Windows'
      shell: pwsh
      working-directory: ${{ inputs.ciproxy-dir }}
      env:
        MASTER_TOKEN: ${{ inputs.master-token }}
        PORT: ${{ inputs.ciproxy-port }}
      run: |
        $ErrorActionPreference = "Stop"
        Set-StrictMode -Version Latest
        $PSNativeCommandUseErrorActionPreference = $true

        go build -o ciproxy.exe

        $exePath = Join-Path (Get-Location) "ciproxy.exe"
        New-Service -Name ciproxy -BinaryPathName $exePath -StartupType Manual

        $vars = @(
          "MASTER_TOKEN=$env:MASTER_TOKEN",
          "PORT=$env:PORT",
        )

        Set-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Services\ciproxy" -Name "Environment" -Value $vars -PropertyType MultiString

        Start-Service -Name ciproxy

    - name: Start ciproxy (Non-Windows)
      id: start-non-windows
      if: runner.os != 'Windows'
      shell: bash --noprofile --norc -euo pipefail {0}
      working-directory: ${{ inputs.ciproxy-dir }}
      env:
        MASTER_TOKEN: ${{ inputs.master-token }}
        PORT: ${{ inputs.ciproxy-port }}
      run: |
        go build -o ciproxy
        nohup ./ciproxy > stdout.log 2> stderr.log &
        CIPROXY_PID=$!
        disown
        sleep 3

        if kill -0 "$CIPROXY_PID" 2>/dev/null; then
          echo "CIPROXY_PID=$CIPROXY_PID" >> "$GITHUB_OUTPUT"
        else
          echo "ERROR: ciproxy crashed immediately!"
          echo "<stdout>"
          cat stdout.log
          echo "</stdout>"
          echo "<stderr>"
          cat stderr.log
          echo "</stderr>"
          exit 1
        fi
