set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)

set(VCPKG_CMAKE_CONFIGURE_OPTIONS -DCMAKE_INSTALL_DO_STRIP=OFF)
set(VCPKG_C_FLAGS "${VCPKG_C_FLAGS} /Zi /arch:AVX2")
set(VCPKG_CXX_FLAGS "${VCPKG_CXX_FLAGS} /Zi /arch:AVX2")
set(VCPKG_LINKER_FLAGS "${VCPKG_LINKER_FLAGS} /DEBUG")
