# SPDX-FileCopyrightText: 2026 Kaito Udagawa <umireon@kaito.tokyo>
#
# SPDX-License-Identifier: Apache-2.0

services:
  dev:
    build:
      context: .
      platforms: [linux/amd64]
    tty: true
    stdin_open: true
