# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

# SPDX-FileCopyrightText: 2026 Kaito Udagawa <umireon@kaito.tokyo>
#
# SPDX-License-Identifier: Apache-2.0

name: Check CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  check-yamllint:
    runs-on: ubuntu-24.04
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Print yamllint version
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        run: yamllint --version

      - name: Check with yamllint
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        run: git ls-files -z '*.yml' | xargs -0 -r yamllint

  check-shellcheck:
    runs-on: ubuntu-24.04
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Print shellcheck version
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        run: shellcheck --version

      - name: Check with shellcheck
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        run: git ls-files -z '*.sh' '*.bash' | xargs -0 -r shellcheck

  check-shfmt:
    runs-on: ubuntu-24.04
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install shfmt with apt
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        run: sudo apt-get update && sudo apt-get install -y shfmt

      - name: Check with shfmt
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        run: git ls-files -z '*.sh' '*.bash' | xargs -0 -r shfmt -i 2 -d

  check-reuse:
    runs-on: ubuntu-24.04
    timeout-minutes: 10

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install check requirements
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        run: |
          python3 -m pip install --user reuse==6.2.0
          printf '%s\n' "${HOME:?}/.local/bin" >>"${GITHUB_PATH:?}"

      - name: Lint with REUSE
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        run: reuse --no-multiprocessing lint
