# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

# SPDX-FileCopyrightText: 2026 Kaito Udagawa <umireon@kaito.tokyo>
#
# SPDX-License-Identifier: Apache-2.0

name: PR Check

on:
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  vcpkg-manifest-windows:
    uses: ./.github/workflows/vcpkg-manifest-windows.yml
    with:
      upload-to-binarycache: false
      runs-on: windows-2022
      vcpkg-version: '2025.08.27'

  vcpkg-ort-windows:
    uses: ./.github/workflows/vcpkg-ort-windows.yml
    with:
      upload-to-binarycache: false
      runs-on: windows-2022
      vcpkg-version: '2025.08.27'
      ort-version: v1.28.0

  vcpkg-manifest-macos:
    uses: ./.github/workflows/vcpkg-manifest-macos.yml
    with:
      upload-to-binarycache: false
      runs-on: macos-15
      DEVELOPER_DIR: /Applications/Xcode_16.4.app
      vcpkg-version: '2025.08.27'

  vcpkg-ort-macos:
    uses: ./.github/workflows/vcpkg-ort-macos.yml
    with:
      upload-to-binarycache: false
      runs-on: macos-15
      DEVELOPER_DIR: /Applications/Xcode_16.4.app
      vcpkg-version: '2025.08.27'
      ort-version: v1.28.0

  vcpkg-manifest-macos-x86_64:
    uses: ./.github/workflows/vcpkg-manifest-macos.yml
    with:
      upload-to-binarycache: false
      runs-on: macos-15
      DEVELOPER_DIR: /Applications/Xcode_16.4.app
      vcpkg-version: '2025.08.27'
      x86_64: true


  vcpkg-ort-macos-x86_64:
    uses: ./.github/workflows/vcpkg-ort-macos.yml
    with:
      upload-to-binarycache: false
      runs-on: macos-15
      DEVELOPER_DIR: /Applications/Xcode_16.4.app
      vcpkg-version: '2025.08.27'
      ort-version: v1.28.0
      x86_64: true
