# SPDX-FileCopyrightText: 2026 Kaito Udagawa <umireon@kaito.tokyo>
#
# SPDX-License-Identifier: Apache-2.0

on:
  workflow_call:
    inputs:
      environment-prepare-devcontainer:
        description: The environment name for the prepare-devcontainer jobs, or empty string for no environment.
        required: true
        type: string
      environment-build-devcontainer:
        description: The environment name for the build-devcontainer jobs, or empty string for no environment.
        required: true
        type: string
      VCPKG_BINARY_SOURCES:
        description: Default VCPKG_BINARY_SOURCES.
        required: true
        type: string
    secrets:
      CIPROXY_MASTER_TOKEN:
        description: CIProxy master token.
        required: false

jobs:
  prepare-devcontainer:
    name: Prepare Dev Container

    runs-on: ubuntu-24.04
    timeout-minutes: 180
    environment: ${{ inputs.environment-prepare-devcontainer }}

    permissions:
      artifact-metadata: write
      attestations: write
      contents: read
      id-token: write
      packages: write

    outputs:
      DEVCONTAINER_IMAGE: "${{ fromJSON(steps.meta.outputs.json).tags[0] }}"

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Resolve azure.archive.ubuntu.com
        id: azure-archive
        shell: bash --noprofile --norc -euo pipefail {0}
        run: getent hosts azure.archive.ubuntu.com | awk 'NR==1 {print "IPADDR=" $1}' >> "$GITHUB_OUTPUT"

      - name: Log in to the GitHub Container registry
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0

      - name: Extract metadata for builder image
        id: meta
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # v6.0.0
        with:
          flavor: |
            latest=auto
          images: ghcr.io/${{ github.repository }}-devcontainer
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=ref,event=tag
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha

      - name: Build and Push builder image (Ubuntu)
        id: push
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7.0.0
        with:
          add-hosts: |
            archive.ubuntu.com:${{ steps.azure-archive.outputs.IPADDR }}
            ports.ubuntu.com:${{ steps.azure-archive.outputs.IPADDR }}
          annotations: ${{ steps.meta.outputs.annotations }}
          context: .devcontainer
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: .devcontainer/Dockerfile
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64
          provenance: mode=max
          push: true
          sbom: true
          tags: ${{ steps.meta.outputs.tags }}

  build-devcontainer:
    name: Build vcpkg for Dev Container

    needs: prepare-devcontainer

    runs-on: ubuntu-24.04
    timeout-minutes: 180
    environment: ${{ inputs.environment-build-devcontainer }}

    permissions:
      contents: read
      packages: read

    container:
      image: ${{ needs.prepare-devcontainer.outputs.DEVCONTAINER_IMAGE }}
      options: --user runner

    env:
      VCPKG_BINARY_SOURCES: ${{ github.ref == 'refs/heads/main' && 'http://127.0.0.1:8080/{name}/{version}/{sha},readwrite' || inputs.VCPKG_BINARY_SOURCES }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Set up Go for ciproxy
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version-file: .github/ciproxy/cmd/go.mod
          cache-dependency-path: .github/ciproxy/cmd/go.sum

      - name: Start ciproxy
        id: ciproxy
        if: github.ref == 'refs/heads/main'
        uses: ./.github/actions/start-ciproxy
        with:
          ciproxy-master-token: ${{ secrets.CIPROXY_MASTER_TOKEN }}
          port: "8080"

      - name: Install dependencies from vcpkg (x64-linux-obs)
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        run: '"$VCPKG_ROOT/vcpkg" install --triplet=x64-linux-obs'

      - name: Finalize ciproxy
        if: github.ref == 'refs/heads/main'
        uses: ./.github/actions/finalize-ciproxy
        with:
          ciproxy-master-token: ${{ secrets.CIPROXY_MASTER_TOKEN }}
          pid: ${{ steps.ciproxy.outputs.PID }}

      - name: Upload ciproxy logs
        if: github.ref == 'refs/heads/main' && always()
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: ciproxy-logs-${{ github.job }}-${{ strategy.job-index }}
          path: |
            ${{ steps.ciproxy.outputs.STDOUT_LOG }}
            ${{ steps.ciproxy.outputs.STDERR_LOG }}
          if-no-files-found: warn
