# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

# SPDX-FileCopyrightText: 2026 Kaito Udagawa <umireon@kaito.tokyo>
#
# SPDX-License-Identifier: Apache-2.0

name: Vcpkg Classic CI

# file: .github/workflows/vcpkg-classic.yml
# author: Kaito Udagawa <umireon@kaito.tokyo>
# date: 2026-05-27

on:
  push:
    branches: [main]
  merge_group:
  pull_request:
    branches: [main]
  schedule:
    - cron: 23 9 * * *
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  config:
    permissions: {}
    outputs:
      VCPKG_BINARY_SOURCES: ${{ steps.config.outputs.VCPKG_BINARY_SOURCES }}
      VCPKG_VERSION: ${{ steps.config.outputs.VCPKG_VERSION }}
    runs-on: ubuntu-slim
    steps:
      - name: Output config
        id: config
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        run: |
          echo 'VCPKG_BINARY_SOURCES=clear;http,https://vcpkg-obs.kaito.tokyo/{name}/{version}/{sha},read' >> "${GITHUB_OUTPUT}"
          echo 'VCPKG_VERSION=2026.04.27' >> "${GITHUB_OUTPUT}"

  vcpkg-classic-windows:
    needs: config
    name: classic on Windows x64
    permissions:
      attestations: write
      contents: read
      id-token: write
    uses: ./.github/workflows/vcpkg-classic-windows.yml
    with:
      job-index: 0
      environment: ${{ github.ref == 'refs/heads/main' && 'production' || '' }}
      VCPKG_VERSION: ${{ needs.config.outputs.VCPKG_VERSION }}
      VCPKG_BINARY_SOURCES: ${{ needs.config.outputs.VCPKG_BINARY_SOURCES }}
      VCPKG_TARGET_TRIPLET: 'x64-windows-static-md-obs'
      VCPKG_PORTS: 'opencv4[core]'
    secrets: inherit

  vcpkg-classic-macos:
    needs: config
    strategy:
      fail-fast: false
      matrix:
        os-xcode:
          - name: Sequoia, Xcode 16.4
            runs-on: macos-15
            DEVELOPER_DIR: /Applications/Xcode_16.4.app
          - name: Tahoe, Xcode 26.5
            runs-on: macos-26
            DEVELOPER_DIR: /Applications/Xcode_26.5.app
        triplets:
          - arm64-osx-obs
          - x64-osx-obs
    name: classic on macOS ${{ matrix.os-xcode.name }}
    permissions:
      attestations: write
      contents: read
      id-token: write
    uses: ./.github/workflows/vcpkg-classic-macos.yml
    with:
      job-index: ${{ strategy.job-index }}
      environment: ${{ github.ref == 'refs/heads/main' && 'production' || '' }}
      runs-on: ${{ matrix.os-xcode.runs-on }}
      DEVELOPER_DIR: ${{ matrix.os-xcode.DEVELOPER_DIR }}
      VCPKG_VERSION: ${{ needs.config.outputs.VCPKG_VERSION }}
      VCPKG_BINARY_SOURCES: ${{ needs.config.outputs.VCPKG_BINARY_SOURCES }}
      VCPKG_TARGET_TRIPLET: ${{ matrix.triplets }}
      VCPKG_PORTS: 'opencv4[core]'
    secrets: inherit

  vcpkg-classic-ubuntu:
    needs: config
    name: classic on Ubuntu x64
    permissions:
      attestations: write
      contents: read
      id-token: write
    uses: ./.github/workflows/vcpkg-classic-ubuntu.yml
    with:
      job-index: 0
      environment: ${{ github.ref == 'refs/heads/main' && 'production' || '' }}
      VCPKG_VERSION: ${{ needs.config.outputs.VCPKG_VERSION }}
      VCPKG_BINARY_SOURCES: ${{ needs.config.outputs.VCPKG_BINARY_SOURCES }}
      VCPKG_TARGET_TRIPLET: 'x64-linux-obs'
      VCPKG_PORTS: 'opencv4[core]'
    secrets: inherit

  accept-vcpkg-classic:
    needs: [vcpkg-classic-windows, vcpkg-classic-macos, vcpkg-classic-ubuntu]
    name: Accept vcpkg-classic
    runs-on: ubuntu-slim
    permissions: {}
    steps:
      - run: echo OK
