# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

# SPDX-FileCopyrightText: 2026 Kaito Udagawa <umireon@kaito.tokyo>
#
# SPDX-License-Identifier: Apache-2.0

name: Vcpkg Manifest CI

# file: .github/workflows/vcpkg-manifest.yml
# author: Kaito Udagawa <umireon@kaito.tokyo>
# version: 1.1.0
# date: 2026-04-03

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: 23 11 * * *
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  vcpkg-manifest-windows:
    permissions:
      attestations: write
      contents: read
      id-token: write
    uses: ./.github/workflows/vcpkg-manifest-windows.yml
    with:
      job-index: 0
      environment: ${{ github.ref == 'refs/heads/main' && 'production' || '' }}
      VCPKG_BINARY_SOURCES: "clear;http,https://vcpkg-obs.kaito.tokyo/{name}/{version}/{sha},read"
      vcpkg-version: '2025.08.27'
    secrets: inherit

  vcpkg-manifest-macos:
    strategy:
      fail-fast: false
      matrix:
        triplet: [arm64-osx-obs, x64-osx-obs]
        os-xcode:
          - name: Sequoia, Xcode 16.4
            runs-on: macos-15
            DEVELOPER_DIR: /Applications/Xcode_16.4.app
          - name: Tahoe, Xcode 26.4
            runs-on: macos-26
            DEVELOPER_DIR: /Applications/Xcode_26.4.app
    permissions:
      attestations: write
      contents: read
      id-token: write
    uses: ./.github/workflows/vcpkg-manifest-macos.yml
    with:
      job-index: ${{ strategy.job-index }}
      environment: ${{ github.ref == 'refs/heads/main' && 'production' || '' }}
      VCPKG_BINARY_SOURCES: "clear;http,https://vcpkg-obs.kaito.tokyo/{name}/{version}/{sha},read"
      vcpkg-version: '2025.08.27'
      runs-on: ${{ matrix.os-xcode.runs-on }}
      DEVELOPER_DIR: ${{ matrix.os-xcode.DEVELOPER_DIR }}
      VCPKG_TARGET_TRIPLET: ${{ matrix.triplet }}
    secrets: inherit

  vcpkg-manifest-ubuntu:
    permissions:
      attestations: write
      contents: read
      id-token: write
    uses: ./.github/workflows/vcpkg-manifest-ubuntu.yml
    with:
      job-index: 0
      environment: ${{ github.ref == 'refs/heads/main' && 'production' || '' }}
      VCPKG_BINARY_SOURCES: "clear;http,https://vcpkg-obs.kaito.tokyo/{name}/{version}/{sha},read"
      vcpkg-version: '2025.08.27'
    secrets: inherit

  accept-vcpkg-manifest:
    name: Accept vcpkg-manifest
    needs: [vcpkg-manifest-windows, vcpkg-manifest-macos, vcpkg-manifest-ubuntu]
    runs-on: ubuntu-slim
    permissions: {}
    steps:
      - name: Accept vcpkg-manifest
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        run: |
          echo 'The workflow vcpkg-manifest has completed successfully.'
