# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

# SPDX-FileCopyrightText: 2026 Kaito Udagawa <umireon@kaito.tokyo>
#
# SPDX-License-Identifier: Apache-2.0

name: Vcpkg ORT (macOS)

on:
  workflow_call:
    inputs:
      environment:
        description: GitHub Actions environment name.
        required: false
        type: string
        default: ''
      runs-on:
        description: GitHub Actions runner label.
        required: true
        type: string
      DEVELOPER_DIR:
        description: Xcode developer directory.
        required: true
        type: string
      vcpkg-version:
        description: The version of microsoft/vcpkg to clone.
        required: true
        type: string
      ort-version:
        description: The version of microsoft/onnxruntime to clone.
        required: true
        type: string
      upload-to-binarycache:
        description: Flag to upload to binarycache.
        required: true
        type: boolean
      x86_64:
        description: Flag to build for x86_64.
        required: false
        type: boolean
        default: false

env:
  HOMEBREW_NO_ANALYTICS: '1'
  HOMEBREW_NO_AUTO_UPDATE: '1'
  HOMEBREW_NO_ENV_HINTS: '1'
  HOMEBREW_NO_INSTALL_CLEANUP: '1'

jobs:
  vcpkg-ort-macos:
    environment: ${{ inputs.environment }}
    runs-on: ${{ inputs.runs-on }}
    timeout-minutes: 180

    env:
      DEVELOPER_DIR: ${{ inputs.DEVELOPER_DIR }}
      VCPKG_ORT_TARGET_TRIPLET: ${{ inputs.x86_64 && 'x64-osx-obs-ort' || 'arm64-osx-obs-ort' }}
      VCPKG_ROOT: ${{ github.workspace }}/vcpkg

    steps:
      - name: Print runner info (macOS)
        id: runner-macos
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        run: |
          printf 'ImageVersion=%s\n' "${ImageVersion:?}" | tee -a "${GITHUB_OUTPUT:?}"
          printf 'macos_product_version=%s\n' "$(sw_vers -productVersion)" | tee -a "${GITHUB_OUTPUT:?}"

      - name: Print Xcode info
        id: xcode
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        run: |
          printf 'version=%s\n' "$(xcodebuild -version | awk 'NR == 1 { print $2 }')" | tee -a "${GITHUB_OUTPUT:?}"
          printf 'build_version=%s\n' "$(xcodebuild -version | awk 'NR == 2 { print $3 }')" | tee -a "${GITHUB_OUTPUT:?}"

      - name: Install pkgconf (macOS)
        id: pkgconf
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        run: |
          brew install pkgconf
          printf 'bindir=%s\n' "$(brew --prefix pkgconf)/bin" >>"${GITHUB_OUTPUT:?}"

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Checkout vcpkg
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: microsoft/vcpkg
          ref: ${{ inputs.vcpkg-version }}
          path: vcpkg
          filter: blob:none
          persist-credentials: false

      - name: Checkout ONNX Runtime
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: microsoft/onnxruntime
          ref: ${{ inputs.ort-version }}
          path: onnxruntime
          filter: blob:none
          submodules: recursive
          persist-credentials: false

      - name: Run bootstrap-vcpkg.sh
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        env:
          PKGCONF_BINDIR: ${{ steps.pkgconf.outputs.bindir }}
        run: |
          env -i \
            DEVELOPER_DIR="${DEVELOPER_DIR:?}" \
            HOME="${HOME:?}" \
            PATH="${PKGCONF_BINDIR:?}:/usr/bin:/bin" \
            VCPKG_ROOT="${VCPKG_ROOT:?}" \
            "${VCPKG_ROOT:?}/bootstrap-vcpkg.sh" -disableMetrics

      - name: Set up vcpkg binary cache
        id: binarycache
        if: inputs.upload-to-binarycache
        uses: ./.github/actions/vcpkg-binarycache/setup
        with:
          binarycache-url: https://vcpkg-obs.kaito.tokyo

      - name: Install vcpkg_ort dependencies (macOS)
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        env:
          PKGCONF_BINDIR: ${{ steps.pkgconf.outputs.bindir }}
          VCPKG_BINARY_SOURCES: ${{ steps.binarycache.outputs.VCPKG_BINARY_SOURCES || 'clear;http,https://vcpkg-obs.kaito.tokyo/{sha},read' }}
        run: |
          env -i \
            DEVELOPER_DIR="${DEVELOPER_DIR:?}" \
            HOME="${HOME:?}" \
            PATH="${PKGCONF_BINDIR:?}:/usr/bin:/bin" \
            VCPKG_BINARY_SOURCES=${VCPKG_BINARY_SOURCES:?} \
            VCPKG_ROOT="${VCPKG_ROOT:?}" \
            "${VCPKG_ROOT:?}/vcpkg" install \
            --triplet="${VCPKG_ORT_TARGET_TRIPLET:?}" \
            --overlay-triplets="${GITHUB_WORKSPACE:?}/vcpkg-triplets" \
            --x-feature=coreml-ep \
            --x-manifest-root="${GITHUB_WORKSPACE:?}/onnxruntime/cmake"

      - name: Upload binary packages
        if: ${{ !cancelled() && inputs.upload-to-binarycache }}
        uses: ./.github/actions/vcpkg-binarycache/upload
        with:
          artifact-directory: ${{ steps.binarycache.outputs.ARTIFACT_DIRECTORY }}
