# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

# SPDX-FileCopyrightText: 2026 Kaito Udagawa <umireon@kaito.tokyo>
#
# SPDX-License-Identifier: Apache-2.0

# file: .github/workflows/vcpkg-manifest-macos.yml
# author: Kaito Udagawa <umireon@kaito.tokyo>
# date: 2026-05-25

on:
  workflow_call:
    inputs:
      environment:
        description: The environment name for this workflow, or empty string for no environment.
        required: true
        type: string
      runs-on:
        description: The runner label to run this workflow on.
        required: true
        type: string
      DEVELOPER_DIR:
        description: The value of DEVELOPER_DIR environment variable.
        required: true
        type: string
      VCPKG_VERSION:
        description: The version of vcpkg to clone.
        required: true
        type: string
      VCPKG_BINARY_SOURCES:
        description: Default VCPKG_BINARY_SOURCES.
        required: true
        type: string

permissions: {}

jobs:
  build-manifest-macos:
    runs-on: ${{ inputs.runs-on }}
    timeout-minutes: 180
    environment: ${{ inputs.environment }}

    permissions:
      attestations: write
      contents: read
      id-token: write

    env:
      DEVELOPER_DIR: '${{ inputs.DEVELOPER_DIR }}'
      VCPKG_VERSION: '${{ inputs.VCPKG_VERSION }}'

    steps:
      - name: Print Xcode version
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        run: |
          xcodebuild -version

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Checkout vcpkg
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: microsoft/vcpkg
          ref: ${{ env.VCPKG_VERSION }}
          persist-credentials: false
          path: vcpkg
          filter: blob:none

      - name: Run bootstrap-vcpkg.sh
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        run: |
          ./vcpkg/bootstrap-vcpkg.sh -disableMetrics

      - name: Set up vcpkg binary cache
        id: binarycache
        if: github.ref == 'refs/heads/main'
        uses: ./.github/actions/vcpkg-binarycache/setup

      - name: Install dependencies from macOS vcpkg (arm64-osx-obs)
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        env:
          VCPKG_BINARY_SOURCES: '${{ steps.binarycache.outputs.VCPKG_BINARY_SOURCES || inputs.VCPKG_BINARY_SOURCES }}'
          VCPKG_ROOT: '${{ github.workspace }}/vcpkg'
        run: |
          vcpkg() {
            env -i \
              DEVELOPER_DIR="$DEVELOPER_DIR" \
              HOME="$HOME" \
              PATH=/usr/bin:/bin:/usr/sbin:/sbin \
              VCPKG_BINARY_SOURCES="$VCPKG_BINARY_SOURCES" \
              VCPKG_ROOT="$VCPKG_ROOT" \
              "$VCPKG_ROOT/vcpkg" "$@"
          }

          vcpkg install --triplet=arm64-osx-obs --x-install-root=vcpkg_arm64_installed

      - name: Install dependencies from macOS vcpkg (x64-osx-obs)
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        env:
          VCPKG_BINARY_SOURCES: '${{ steps.binarycache.outputs.VCPKG_BINARY_SOURCES || inputs.VCPKG_BINARY_SOURCES }}'
          VCPKG_ROOT: '${{ github.workspace }}/vcpkg'
        run: |
          vcpkg() {
            env -i \
              DEVELOPER_DIR="$DEVELOPER_DIR" \
              HOME="$HOME" \
              PATH=/usr/bin:/bin:/usr/sbin:/sbin \
              VCPKG_BINARY_SOURCES="$VCPKG_BINARY_SOURCES" \
              VCPKG_ROOT="$VCPKG_ROOT" \
              "$VCPKG_ROOT/vcpkg" "$@"
          }

          vcpkg install --triplet=x64-osx-obs --x-install-root=vcpkg_x64_installed

      - name: Upload binary packages
        if: ${{ !cancelled() && github.ref == 'refs/heads/main' }}
        uses: ./.github/actions/vcpkg-binarycache/upload
        with:
          artifact-directory: ${{ steps.binarycache.outputs.ARTIFACT_DIRECTORY }}
