# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

# SPDX-FileCopyrightText: 2026 Kaito Udagawa <umireon@kaito.tokyo>
#
# SPDX-License-Identifier: Apache-2.0

name: Vcpkg ORT CI

# file: .github/workflows/vcpkg-ort.yml
# author: Kaito Udagawa <umireon@kaito.tokyo>
# version: 1.1.0
# date: 2026-04-03

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: 23 9 * * *
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  vcpkg-ort-windows:
    strategy:
      fail-fast: false
      matrix:
        ort-version: [v1.24.1, v1.24.4]
    permissions:
      attestations: write
      contents: read
      id-token: write
    uses: ./.github/workflows/vcpkg-ort-windows.yml
    with:
      job-index: ${{ strategy.job-index }}
      environment: ${{ github.ref == 'refs/heads/main' && 'production' || '' }}
      VCPKG_BINARY_SOURCES: "clear;http,https://vcpkg-obs.kaito.tokyo/{name}/{version}/{sha},read"
      ort-version: ${{ matrix.ort-version }}
    secrets: inherit

  vcpkg-ort-macos:
    strategy:
      fail-fast: false
      matrix:
        arch: [arm64, x86_64]
        ort-version: [v1.24.1, v1.24.4]
        os-xcode:
          - name: Sequoia, Xcode 16.4
            runs-on: macos-15
            DEVELOPER_DIR: /Applications/Xcode_16.4.app
          - name: Tahoe, Xcode 26.4
            runs-on: macos-26
            DEVELOPER_DIR: /Applications/Xcode_26.4.app
    permissions:
      attestations: write
      contents: read
      id-token: write
    uses: ./.github/workflows/vcpkg-ort-macos.yml
    with:
      job-index: ${{ strategy.job-index }}
      environment: ${{ github.ref == 'refs/heads/main' && 'production' || '' }}
      VCPKG_BINARY_SOURCES: "clear;http,https://vcpkg-obs.kaito.tokyo/{name}/{version}/{sha},read"
      ort-version: ${{ matrix.ort-version }}
      runs-on: ${{ matrix.os-xcode.runs-on }}
      DEVELOPER_DIR: ${{ matrix.os-xcode.DEVELOPER_DIR }}
      arch: ${{ matrix.arch }}
    secrets: inherit

  vcpkg-ort-ubuntu:
    strategy:
      fail-fast: false
      matrix:
        ort-version: [v1.24.1, v1.24.4]
    permissions:
      attestations: write
      contents: read
      id-token: write
    uses: ./.github/workflows/vcpkg-ort-ubuntu.yml
    with:
      job-index: ${{ strategy.job-index }}
      environment: ${{ github.ref == 'refs/heads/main' && 'production' || '' }}
      VCPKG_BINARY_SOURCES: "clear;http,https://vcpkg-obs.kaito.tokyo/{name}/{version}/{sha},read"
      ort-version: ${{ matrix.ort-version }}
    secrets: inherit

  accept-vcpkg-ort:
    name: Accept vcpkg-ort
    needs: [vcpkg-ort-windows, vcpkg-ort-macos, vcpkg-ort-ubuntu]
    runs-on: ubuntu-slim
    permissions: {}
    steps:
      - name: Accept vcpkg-ort
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        run: |
          echo 'The workflow vcpkg-ort has completed successfully.'
