# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

# SPDX-FileCopyrightText: 2026 Kaito Udagawa <umireon@kaito.tokyo>
#
# SPDX-License-Identifier: Apache-2.0

# file: .github/workflows/vcpkg-manifest-windows.yml
# author: Kaito Udagawa <umireon@kaito.tokyo>
# version: 1.1.1
# date: 2026-04-05

on:
  workflow_call:
    inputs:
      job-index:
        description: The job index for logging.
        required: true
        type: number
      environment:
        description: The environment name for this workflow, or empty string for no environment
        required: true
        type: string
      VCPKG_BINARY_SOURCES:
        description: Default VCPKG_BINARY_SOURCES.
        required: true
        type: string
      vcpkg-version:
        description: The version of vcpkg to clone.
        required: true
        type: string

    secrets:
      CIPROXY_MASTER_TOKEN:
        description: CIProxy master token.
        required: false

permissions: {}

jobs:
  build-manifest-windows:
    runs-on: windows-2022
    timeout-minutes: 180
    environment: ${{ inputs.environment }}

    permissions:
      attestations: write
      contents: read
      id-token: write

    env:
      CLEAN_PWSH_ENV: '${{ github.workspace }}/.github/scripts/clean-env-windows.ps1'
      FILTERED_PATH: 'C:\ProgramData\chocolatey\bin;C:\Program Files\CMake\bin;C:\Program Files\Git\cmd;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32;C:\Windows'
      ROOT_VCPKG_ROOT: '${{ github.workspace }}\vcpkg'

    steps:
      - name: Enable Windows long path
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          Set-StrictMode -Version Latest
          $PSNativeCommandUseErrorActionPreference = $true

          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -Value 1

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Set up Go for ciproxy
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: .github/actions/ciproxy/cmd/go.mod
          cache-dependency-path: .github/actions/ciproxy/cmd/go.sum

      - name: Print CMake version on Windows
        shell: pwsh
        env:
          PATH: '${{ env.FILTERED_PATH }}'
        run: |
          $ErrorActionPreference = 'Stop'
          Set-StrictMode -Version Latest
          $PSNativeCommandUseErrorActionPreference = $true

          . $env:CLEAN_PWSH_ENV

          cmake --version

      - name: Print Ninja version on Windows
        shell: pwsh
        env:
          PATH: '${{ env.FILTERED_PATH }}'
        run: |
          $ErrorActionPreference = 'Stop'
          Set-StrictMode -Version Latest
          $PSNativeCommandUseErrorActionPreference = $true

          . $env:CLEAN_PWSH_ENV

          ninja --version

      - name: Checkout vcpkg
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: microsoft/vcpkg
          ref: ${{ inputs.vcpkg-version }}
          persist-credentials: false
          path: vcpkg
          filter: "blob:none"

      - name: Run bootstrap-vcpkg.bat
        shell: pwsh
        env:
          PATH: '${{ env.FILTERED_PATH }}'
          VCPKG_ROOT: '${{ env.ROOT_VCPKG_ROOT }}'
        run: |
          $ErrorActionPreference = 'Stop'
          Set-StrictMode -Version Latest
          $PSNativeCommandUseErrorActionPreference = $true

          . $env:CLEAN_PWSH_ENV

          $bootstrapVcpkgPath = "$env:VCPKG_ROOT\bootstrap-vcpkg.bat"
          & $bootstrapVcpkgPath -disableMetrics

      - name: Start ciproxy
        id: ciproxy
        if: github.ref == 'refs/heads/main'
        uses: ./.github/actions/ciproxy/start
        with:
          ciproxy-master-token: ${{ secrets.CIPROXY_MASTER_TOKEN }}

      - name: Install dependencies from vcpkg (Windows x64)
        shell: pwsh
        env:
          PATH: '${{ env.FILTERED_PATH }}'
          VCPKG_BINARY_SOURCES: '${{ steps.ciproxy.outputs.VCPKG_BINARY_SOURCES || inputs.VCPKG_BINARY_SOURCES }}'
          VCPKG_ROOT: '${{ env.ROOT_VCPKG_ROOT }}'
        run: |
          $ErrorActionPreference = 'Stop'
          Set-StrictMode -Version Latest
          $PSNativeCommandUseErrorActionPreference = $true

          . $env:CLEAN_PWSH_ENV

          $vcpkgPath = "$env:VCPKG_ROOT\vcpkg.exe"
          & $vcpkgPath install --x-install-root=.deps_vendor/vcpkg_installed --triplet=x64-windows-static-md-obs

      - name: Stop ciproxy and upload binary packages
        if: github.ref == 'refs/heads/main'
        uses: ./.github/actions/ciproxy/finalize
        with:
          ciproxy-master-token: ${{ secrets.CIPROXY_MASTER_TOKEN }}
          pid: ${{ steps.ciproxy.outputs.PID }}

      - name: Upload ciproxy logs
        if: github.ref == 'refs/heads/main' && always()
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: ciproxy-logs-${{ github.job }}-${{ inputs.job-index }}
          path: |
            ${{ steps.ciproxy.outputs.STDOUT_LOG }}
            ${{ steps.ciproxy.outputs.STDERR_LOG }}
          if-no-files-found: warn
