# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

# SPDX-FileCopyrightText: 2026 Kaito Udagawa <umireon@kaito.tokyo>
#
# SPDX-License-Identifier: Apache-2.0

name: Vcpkg Manifest CI

# file: .github/workflows/vcpkg-manifest.yml
# author: Kaito Udagawa <umireon@kaito.tokyo>
# date: 2026-05-27

on:
  push:
    branches: [main]
  merge_group:
  pull_request:
    branches: [main]
  schedule:
    - cron: 23 11 * * *
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  config:
    uses: ./.github/workflows/workflow-config.yml

  vcpkg-manifest-windows:
    needs: config
    name: Manifest on Windows x64
    permissions:
      attestations: write
      contents: read
      id-token: write
    uses: ./.github/workflows/vcpkg-manifest-windows.yml
    with:
      job-index: 0
      environment: ${{ github.ref == 'refs/heads/main' && 'production' || '' }}
      VCPKG_VERSION: ${{ fromJSON(needs.config.outputs.config).VCPKG_VERSION }}
      VCPKG_BINARY_SOURCES: ${{ fromJSON(needs.config.outputs.config).VCPKG_BINARY_SOURCES }}
    secrets: inherit

  vcpkg-manifest-macos:
    needs: config
    strategy:
      fail-fast: false
      matrix:
        os-xcode:
          - name: Sequoia, Xcode 16.4
            runs-on: macos-15
            DEVELOPER_DIR: /Applications/Xcode_16.4.app
          - name: Tahoe, Xcode 26.5
            runs-on: macos-26
            DEVELOPER_DIR: /Applications/Xcode_26.5.app
    name: Manifest on macOS ${{ matrix.os-xcode.name }}
    permissions:
      attestations: write
      contents: read
      id-token: write
    uses: ./.github/workflows/vcpkg-manifest-macos.yml
    with:
      job-index: ${{ strategy.job-index }}
      environment: ${{ github.ref == 'refs/heads/main' && 'production' || '' }}
      runs-on: ${{ matrix.os-xcode.runs-on }}
      DEVELOPER_DIR: ${{ matrix.os-xcode.DEVELOPER_DIR }}
      VCPKG_VERSION: ${{ fromJSON(needs.config.outputs.config).VCPKG_VERSION }}
      VCPKG_BINARY_SOURCES: ${{ fromJSON(needs.config.outputs.config).VCPKG_BINARY_SOURCES }}
    secrets: inherit

  vcpkg-manifest-macos-arm64-14:
    needs: config
    strategy:
      fail-fast: false
      matrix:
        os-xcode:
          - name: Tahoe, Xcode 26.5
            runs-on: macos-26
            DEVELOPER_DIR: /Applications/Xcode_26.5.app
    name: Manifest on macOS ${{ matrix.os-xcode.name }}
    permissions:
      attestations: write
      contents: read
      id-token: write
    uses: ./.github/workflows/vcpkg-manifest-macos-arm64-14.yml
    with:
      job-index: ${{ strategy.job-index }}
      environment: ${{ github.ref == 'refs/heads/main' && 'production' || '' }}
      runs-on: ${{ matrix.os-xcode.runs-on }}
      DEVELOPER_DIR: ${{ matrix.os-xcode.DEVELOPER_DIR }}
      VCPKG_VERSION: ${{ fromJSON(needs.config.outputs.config).VCPKG_VERSION }}
      VCPKG_BINARY_SOURCES: ${{ fromJSON(needs.config.outputs.config).VCPKG_BINARY_SOURCES }}
    secrets: inherit

  vcpkg-manifest-ubuntu:
    needs: config
    name: Manifest on Ubuntu x64
    permissions:
      attestations: write
      contents: read
      id-token: write
    uses: ./.github/workflows/vcpkg-manifest-ubuntu.yml
    with:
      job-index: 0
      environment: ${{ github.ref == 'refs/heads/main' && 'production' || '' }}
      VCPKG_VERSION: ${{ fromJSON(needs.config.outputs.config).VCPKG_VERSION }}
      VCPKG_BINARY_SOURCES: ${{ fromJSON(needs.config.outputs.config).VCPKG_BINARY_SOURCES }}
    secrets: inherit

  accept-vcpkg-manifest:
    needs: [vcpkg-manifest-windows, vcpkg-manifest-macos, vcpkg-manifest-macos-arm64-14, vcpkg-manifest-ubuntu]
    name: Accept vcpkg-manifest
    runs-on: ubuntu-slim
    permissions: {}
    steps:
      - run: echo OK
