# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

# SPDX-FileCopyrightText: 2026 Kaito Udagawa <umireon@kaito.tokyo>
#
# SPDX-License-Identifier: Apache-2.0

name: Vcpkg ORT CI

# file: .github/workflows/vcpkg-ort.yml
# author: Kaito Udagawa <umireon@kaito.tokyo>
# date: 2026-06-18

on:
  push:
    branches: [main]
  merge_group:
  pull_request:
    branches: [main]
  schedule:
    - cron: 23 9 * * *
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci-config:
    permissions:
      contents: read
    uses: ./.github/workflows/ci-config.yml

  vcpkg-ort-windows:
    needs: ci-config
    name: Vcpkg ORT Windows
    permissions:
      attestations: write
      contents: read
      id-token: write
    uses: ./.github/workflows/vcpkg-ort-windows.yml
    with:
      environment: ${{ github.ref == 'refs/heads/main' && 'production' || '' }}
      WINDOWS_SDK_VERSION: ${{ needs.ci-config.outputs.WINDOWS_SDK_VERSION }}
      VCPKG_VERSION: ${{ needs.ci-config.outputs.VCPKG_ORT_VERSION }}
      ORT_VERSION: ${{ needs.ci-config.outputs.ORT_VERSION }}
      VCPKG_BINARY_SOURCES: ${{ needs.ci-config.outputs.VCPKG_BINARY_SOURCES }}

  vcpkg-ort-macos:
    permissions:
      attestations: write
      contents: read
      id-token: write
    uses: ./.github/workflows/vcpkg-ort-macos.yml
    with:
      environment: ${{ github.ref == 'refs/heads/main' && 'production' || '' }}
      runs-on: macos-15
      DEVELOPER_DIR: /Applications/Xcode_16.4.app
      vcpkg-version: '2025.08.27'
      ort-version: 'v1.28.0'

  vcpkg-ort-macos-x86_64:
    permissions:
      attestations: write
      contents: read
      id-token: write
    uses: ./.github/workflows/vcpkg-ort-macos.yml
    with:
      environment: ${{ github.ref == 'refs/heads/main' && 'production' || '' }}
      runs-on: macos-15
      DEVELOPER_DIR: /Applications/Xcode_16.4.app
      vcpkg-version: '2025.08.27'
      ort-version: 'v1.28.0'
      x86_64: true

  accept-vcpkg-ort:
    needs:
      - vcpkg-ort-windows
      - vcpkg-ort-macos
      - vcpkg-ort-macos-x86_64
    name: Accept vcpkg-ort
    runs-on: ubuntu-slim
    permissions: {}
    env:
      VCPKG_ORT_WINDOWS_RESULT: ${{ needs.vcpkg-ort-windows.result }}
      VCPKG_ORT_MACOS_RESULT: ${{ needs.vcpkg-ort-macos.result }}
      VCPKG_ORT_MACOS_X86_64_RESULT: ${{ needs.vcpkg-ort-macos-x86_64.result }}
    steps:
      - name: Accept vcpkg-ort
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        run: |
          [[ "${VCPKG_ORT_WINDOWS_RESULT:?}" == 'success' ]] && \
          [[ "${VCPKG_ORT_MACOS_RESULT:?}" == 'success' ]] && \
          [[ "${VCPKG_ORT_MACOS_X86_64_RESULT:?}" == 'success' ]] && \
          printf 'OK\n'
