# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

# SPDX-FileCopyrightText: 2026 Kaito Udagawa <umireon@kaito.tokyo>
#
# SPDX-License-Identifier: Apache-2.0

name: Vcpkg ORT (Windows)

on:
  workflow_call:
    inputs:
      upload-to-binarycache:
        description: Upload to binarycache.
        required: true
        type: boolean
      environment:
        description: GitHub Actions environment name.
        required: false
        type: string
        default: ''
      runs-on:
        description: GitHub Actions runner label.
        required: true
        type: string
      vcpkg-version:
        description: The version of microsoft/vcpkg to clone.
        required: true
        type: string
      ort-version:
        description: The version of microsoft/onnxruntime to clone.
        required: true
        type: string

jobs:
  vcpkg-ort-windows-x64:
    environment: ${{ inputs.environment }}
    runs-on: ${{ inputs.runs-on }}
    timeout-minutes: 180

    env:
      VCPKG_ORT_TARGET_TRIPLET: x64-windows-static-md-obs-ort
      VCPKG_ROOT: ${{ github.workspace }}/vendor/vcpkg

    steps:
      - name: Enable Windows long path
        shell: pwsh -Command "Set-StrictMode -Version Latest; $ErrorActionPreference = 'Stop'; $PSNativeCommandUseErrorActionPreference = $true; . '{0}'"
        run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -Value 1

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Checkout microsoft/vcpkg
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: microsoft/vcpkg
          ref: ${{ inputs.vcpkg-version }}
          path: vendor/vcpkg
          filter: blob:none
          persist-credentials: false

      - name: Checkout microsoft/onnxruntime
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: microsoft/onnxruntime
          ref: ${{ inputs.ort-version }}
          path: vendor/onnxruntime
          filter: blob:none
          persist-credentials: false

      - name: Run bootstrap-vcpkg.bat
        shell: pwsh -Command "Set-StrictMode -Version Latest; $ErrorActionPreference = 'Stop'; $PSNativeCommandUseErrorActionPreference = $true; . '{0}'"
        run: |
          $env:Path = 'C:\Program Files\Git\cmd;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32;C:\Windows'
          & (Join-Path $env:VCPKG_ROOT 'bootstrap-vcpkg.bat') -disableMetrics

      - name: Set up vcpkg binary cache
        id: binarycache
        if: inputs.upload-to-binarycache
        uses: ./.github/actions/vcpkg-binarycache/setup
        with:
          binarycache-url: https://vcpkg-obs.kaito.tokyo

      - name: Install vcpkg_ort dependencies (Windows)
        shell: pwsh -Command "Set-StrictMode -Version Latest; $ErrorActionPreference = 'Stop'; $PSNativeCommandUseErrorActionPreference = $true; . '{0}'"
        env:
          VCPKG_BINARY_SOURCES: ${{ steps.binarycache.outputs.VCPKG_BINARY_SOURCES || 'clear;http,https://vcpkg-obs.kaito.tokyo/{sha},read' }}
        run: |
          $LAUNCH_DEVSHELL = Join-Path (vswhere -version '[18,19)' -property installationPath) 'Common7' 'Tools' 'Launch-VsDevShell.ps1'
          $VCPKG_COMMAND = Join-Path $env:VCPKG_ROOT 'vcpkg.exe'

          $env:Path = 'C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32;C:\Windows'
          & $LAUNCH_DEVSHELL -Arch amd64 -HostArch amd64 -SkipAutomaticLocation

          $env:VCPKG_DISABLE_METRICS = '1'
          $env:VCPKG_FORCE_DOWNLOADED_BINARIES = '1'
          & $VCPKG_COMMAND install `
            --triplet $env:VCPKG_ORT_TARGET_TRIPLET `
            --overlay-triplets (Join-Path $env:GITHUB_WORKSPACE 'vcpkg-triplets') `
            --x-install-root (Join-Path $env:GITHUB_WORKSPACE 'vcpkg_ort_installed') `
            --x-manifest-root (Join-Path $env:GITHUB_WORKSPACE 'vendor' 'onnxruntime' 'cmake')

      - name: Upload binary packages
        if: ${{ !cancelled() && inputs.upload-to-binarycache }}
        uses: ./.github/actions/vcpkg-binarycache/upload
        with:
          artifact-directory: ${{ steps.binarycache.outputs.ARTIFACT_DIRECTORY }}
