# SPDX-FileCopyrightText: 2026 Kaito Udagawa <umireon@kaito.tokyo>
#
# SPDX-License-Identifier: Apache-2.0

on:
  workflow_call:
    inputs:
      environment-prepare-devcontainer:
        description: The environment name for the prepare-devcontainer jobs, or empty string for no environment.
        required: true
        type: string
      environment-build-devcontainer:
        description: The environment name for the build-devcontainer jobs, or empty string for no environment.
        required: true
        type: string
      vcpkg-binary-sources-readonly-url:
        description: The URL of the read-only vcpkg binary sources.
        required: true
        type: string
      ciproxy-token-url:
        description: Token URL.
        required: true
        type: string
      ciproxy-binarycache-url:
        description: Binarycache URL.
        required: true
        type: string
      ciproxy-binarycache-readwrite-url:
        description: Binarycache Readwrite URL.
        required: true
        type: string
    secrets:
      CIPROXY_MASTER_TOKEN:
        description: The master token for ciproxy.
        required: false

jobs:
  prepare-devcontainer:
    name: Prepare Dev Container

    runs-on: ubuntu-24.04
    timeout-minutes: 180
    environment: ${{ inputs.environment-prepare-devcontainer }}

    permissions:
      artifact-metadata: write
      attestations: write
      contents: read
      id-token: write
      packages: write

    outputs:
      DEVCONTAINER_IMAGE: "${{ fromJSON(steps.meta.outputs.json).tags[0] }}"

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Extract vcpkg configuration
        id: vcpkg-configuration
        uses: ./.github/actions/extract-vcpkg-configuration
        with:
          path: ${{ github.workspace }}/vcpkg-configuration.json

      - name: Image info
        id: image-info
        shell: bash --noprofile --norc -euo pipefail {0}
        env:
          DEVCONTAINER_DOCKERFILE_HASH: ${{ hashFiles('.devcontainer/Dockerfile', 'vcpkg-configuration.json') }}
        run: |
          echo "RAW_IMAGE_NAME=$GITHUB_REPOSITORY-devcontainer" >> "$GITHUB_OUTPUT"
          echo "IMAGE_TAG_TEMPLATE=utc-{{date 'YYYYMMDD'}}-${DEVCONTAINER_DOCKERFILE_HASH:0:7}" >> "$GITHUB_OUTPUT"

      - name: Log in to the GitHub Container registry
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0

      - name: Extract metadata for builder image
        id: meta
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # v6.0.0
        with:
          images: ghcr.io/${{ steps.image-info.outputs.RAW_IMAGE_NAME }}
          tags: |
            type=raw,value=${{ steps.image-info.outputs.IMAGE_TAG_TEMPLATE }},priority=10000
            type=raw,value=latest

      - name: Check if builder image already exists
        id: check-image
        shell: bash --noprofile --norc -euo pipefail {0}
        env:
          DEVCONTAINER_IMAGE: ${{ fromJSON(steps.meta.outputs.json).tags[0] }}
        run: |
          if docker manifest inspect "$DEVCONTAINER_IMAGE"; then
            echo "EXISTS=true" >> "$GITHUB_OUTPUT"
          else
            echo "EXISTS=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Resolve azure.archive.ubuntu.com
        id: azure-archive
        if: steps.check-image.outputs.EXISTS == 'false'
        shell: bash --noprofile --norc -euo pipefail {0}
        run: getent hosts azure.archive.ubuntu.com | awk 'NR==1 {print "IPADDR=" $1}' >> "$GITHUB_OUTPUT"

      - name: Build and Push builder image (Ubuntu)
        id: push
        if: steps.check-image.outputs.EXISTS == 'false'
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7.0.0
        with:
          add-hosts: |
            archive.ubuntu.com:${{ steps.azure-archive.outputs.IPADDR }}
            ports.ubuntu.com:${{ steps.azure-archive.outputs.IPADDR }}
          build-args: |
            ARG_VCPKG_DEFAULT_REGISTRY_BASELINE=${{ steps.vcpkg-configuration.outputs.DEFAULT_REGISTRY_BASELINE }}
          context: .devcontainer
          file: .devcontainer/Dockerfile
          labels: ${{ steps.meta.outputs.labels }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      - name: Extract subject name of builder image
        id: subject
        if: steps.check-image.outputs.EXISTS == 'false'
        shell: bash --noprofile --norc -euo pipefail {0}
        env:
          DEVCONTAINER_IMAGE: ${{ fromJSON(steps.meta.outputs.json).tags[0] }}
        run: echo "SUBJECT_NAME=${DEVCONTAINER_IMAGE%:*}" >> "$GITHUB_OUTPUT"

      - name: Generate artifact attestation for builder image (Ubuntu)
        if: steps.check-image.outputs.EXISTS == 'false'
        uses: actions/attest@e18a799f23337c367f76b067253d6f53abc6f03d # v4.1.0
        with:
          subject-name: ${{ steps.subject.outputs.SUBJECT_NAME }}
          subject-digest: ${{ steps.push.outputs.digest }}

  build-devcontainer:
    name: Build vcpkg for Dev Container

    needs: prepare-devcontainer

    runs-on: ubuntu-24.04
    timeout-minutes: 180
    environment: ${{ inputs.environment-build-devcontainer }}

    permissions:
      contents: read
      packages: read

    container:
      image: ${{ needs.prepare-devcontainer.outputs.DEVCONTAINER_IMAGE }}
      options: --user runner

    env:
      VCPKG_BINARY_SOURCES: "clear;http,${{ (github.ref == 'refs/heads/main') && 'http://127.0.0.1:8080/{name}/{version}/{sha},readwrite' || format('{0},read', inputs.vcpkg-binary-sources-readonly-url) }}"
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Set up Go for ciproxy
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version-file: ciproxy/go.mod
          cache-dependency-path: ciproxy/go.sum

      - name: Start ciproxy
        id: ciproxy
        if: github.ref == 'refs/heads/main'
        uses: ./.github/actions/start-ciproxy
        with:
          path: ciproxy
          port: "8080"
          ciproxy-master-token: ${{ secrets.CIPROXY_MASTER_TOKEN }}
          ciproxy-token-url: ${{ inputs.ciproxy-token-url }}
          ciproxy-binarycache-url: ${{ inputs.ciproxy-binarycache-url }}
          ciproxy-binarycache-readwrite-url: ${{ inputs.ciproxy-binarycache-readwrite-url }}

      - name: Install dependencies from vcpkg (x64-linux-obs)
        shell: bash --noprofile --norc -euo pipefail {0}
        run: '"$VCPKG_ROOT/vcpkg" install --triplet=x64-linux-obs'

      - name: Finalize ciproxy
        if: github.ref == 'refs/heads/main'
        uses: ./.github/actions/finalize-ciproxy
        with:
          pid: ${{ steps.ciproxy.outputs.PID }}
          port: "8080"
          ciproxy-master-token: ${{ secrets.CIPROXY_MASTER_TOKEN }}

      - name: Upload ciproxy logs
        if: github.ref == 'refs/heads/main' && always()
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: ciproxy-logs-${{ github.job }}-${{ strategy.job-index }}
          path: |
            ${{ steps.ciproxy.outputs.CIPROXY_STDOUT_LOG }}
            ${{ steps.ciproxy.outputs.CIPROXY_STDERR_LOG }}
          if-no-files-found: warn
